---
title: "ISYE 6644 - Project"
output: html_notebook
---

```{r initialization}
# clear environment
rm(list=ls())
# libraries
library(EpiModel)
```


# Homogenous Population Model 


```{r homogenous pop model setup}
n = 500 # number of people
nw <- network_initialize(n = n) 
formation <- ~edges
target.stats <- 3*n/4

coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 3)
est <- netest(nw, formation, target.stats, coef.diss) 
```

## Diagnostics
```{r homogenous model diagnostics}
dx <- netdx(est, nsims = 10, nsteps = 100, ncores = 5,
            nwstats.formula = ~edges + meandeg + degree(0:4))
plot(dx)
print(dx)
```

## SI Model

```{r si homongenous model sim}

start <- Sys.time()
results_SI <- vector("list", length = 3)

for (i in 1:3){
  param <- param.net(inf.prob = ppois(n/100*0.4,n/100))
  
  init <- init.net(i.num = 5)
  control <- control.net(type = "SI", nsteps = 100, nsims = 2, ncores = 5)
  sim <- netsim(est, param, init, control) 
  results_SI[[i]] <- as.data.frame(sim, out = "mean")
}

plot(sim, y = c("s.num", "i.num"), legend = TRUE)
plot(sim, type = "network", col.status = TRUE, at = 1, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 30, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 50, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 100, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)

end <- Sys.time()
end - start
```

## SI Model with Vaccine Intervention

```{r si homogenous model w/ intervention sim}
start <- Sys.time()
results_SIV <- vector("list", length = 3)

for (i in 1:3){
  param <- param.net(inf.prob = ppois(n/100*0.4,n/100),
                     inter.eff = 0.9, 
                     inter.start = 30)
  
  init <- init.net(i.num = 5)
  control <- control.net(type = "SI", nsteps = 100, nsims = 3, ncores = 5)
  sim <- netsim(est, param, init, control) 
  results_SIV[[i]] <- as.data.frame(sim, out = "mean")
}

plot(sim, y = c("s.num", "i.num"), legend = TRUE)
plot(sim, type = "network", col.status = TRUE, at = 1, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 30, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 50, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 100, sims = 1)
legend("topright", legend = c("Susceptible", "Infected"), 
       col = c("#5cafe7", "#e77e90"), pch = 16)

end <- Sys.time()
end - start
```



## SIR Model

```{r SIR homogenous model sim}
start <- Sys.time()
results_SIR <- vector("list", length = 3)

for (i in 1:3){
  param <- param.net(inf.prob = ppois(n/100*0.4,n/100), 
                    rec.rate = 0.01)
  
  init <- init.net(i.num = 5, r.num = 0)
  control <- control.net(type = "SIR", nsteps = 200, nsims = 3, ncores = 5)
  sim <- netsim(est, param, init, control) 
  results_SIR[[i]] <- as.data.frame(sim, out = "mean")
}

plot(sim, y = c("s.num", "i.num", "r.num"), legend = TRUE)
plot(sim, type = "network", col.status = TRUE, at = 1, sims = 1)
legend("topright", legend = c("Susceptible", "Infected", "Recovered"), 
       col = c("#5cafe7", "#e77e90", "#89da7b"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 50, sims = 1)
legend("topright", legend = c("Susceptible", "Infected", "Recovered"), 
       col = c("#5cafe7", "#e77e90", "#89da7b"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 100, sims = 1)
legend("topright", legend = c("Susceptible", "Infected", "Recovered"), 
       col = c("#5cafe7", "#e77e90", "#89da7b"), pch = 16)
plot(sim, type = "network", col.status = TRUE, at = 200, sims = 1)
legend("topright", legend = c("Susceptible", "Infected", "Recovered"), 
       col = c("#5cafe7", "#e77e90", "#89da7b"), pch = 16)

end <- Sys.time()
end - start
```
## Data Output

```{r write out data to csvs}

average_results <- function(df_list) {

  # Reduce the list by summing up corresponding elements
  summed_df <- Reduce("+", df_list)
  
  # Divide by the number of data frames to get the average
  averaged_df <- summed_df / length(df_list)
  
  return(averaged_df)
}

df_SI <- average_results(results_SI)
df_SIV <- average_results(results_SIV)
df_SIR <- average_results(results_SIR)

write.csv(df_SI, "SI_homogenous.csv")
write.csv(df_SIV, "SI_vaccine_homogenous.csv")
write.csv(df_SIR, "SIR_homogenous.csv")

```



# Heterogenous Population Model

## Model Setup
```{r heterogenous pop model setup}
# clear environment
rm(list=ls())

n = 500 
nw_het <- network_initialize(n = n) 
nw_het <- set_vertex_attribute(nw_het, attrname = "group", value = rep(1:2, each = n/2))
formation_het <- ~edges + nodematch("group")
target.stats_het <- c(3*n/4, n/4)

coef.diss_het <- dissolution_coefs(dissolution = ~offset(edges), duration = 3)
est_het <- netest(nw_het, formation_het, target.stats_het, coef.diss_het) 
```

## Diagnostics
```{r heterogenous model diagnostics}
dx <- netdx(est_het, nsims = 10, nsteps = 300, ncores = 5,
            nwstats.formula = ~edges + meandeg + degree(0:4, by = "group"))
plot(dx)
print(dx)
```


## SI model

```{r SI heterogenous model sim}
start <- Sys.time()
results_SI_het <- vector("list", length = 3)

for (i in 1:3){
  param <- param.net(inf.prob = ppois(n/100*0.4,n/100), 
                     inf.prob.g2 = ppois(n/100*0.7,n/100))
  
  init <- init.net(i.num = 2, i.num.g2 = 3)
  control <- control.net(type = "SI", nsteps = 100, nsims = 3, ncores = 5)
  sim <- netsim(est_het, param, init, control) 
  results_SI_het[[i]] <- as.data.frame(sim, out = "mean")
}

plot(sim, y = c("s.num", "i.num"), legend = TRUE)
plot(sim, y = c("s.num", "s.num.g2", "i.num", "i.num.g2"), legend = TRUE)
plot(sim, type = "network", col.status = TRUE, at = 1, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 30, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 50, sims = 1, shp.g2 = "square")
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 100, sims = 1, shp.g2 = "square")
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))


end <- Sys.time()
end - start
```



## SI Model w/ Vaccine Intervention
```{r SI heterogenous model w/ intervention}
start <- Sys.time()
results_SIV_het <- vector("list", length = 3)

for (i in 1:3){
  param <- param.net(inf.prob = ppois(n/100*0.4,n/100), 
                     inf.prob.g2 = ppois(n/100*0.7,n/100),
                     inter.eff = 0.9, 
                     inter.start = 30)
  
  init <- init.net(i.num = 2, i.num.g2 = 3)
  control <- control.net(type = "SI", nsteps = 100, nsims = 3, ncores = 5)
  sim <- netsim(est_het, param, init, control) 
  results_SIV_het[[i]] <- as.data.frame(sim, out = "mean")
}

plot(sim, y = c("s.num", "i.num"), legend = TRUE)
plot(sim, y = c("s.num", "s.num.g2", "i.num", "i.num.g2"), legend = TRUE)
plot(sim, type = "network", col.status = TRUE, at = 1, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 30, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 50, sims = 1, shp.g2 = "square")
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 100, sims = 1, shp.g2 = "square")
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90"), pch = c(16, 15, 16, 15))
end <- Sys.time()
end - start
```

# SIR Model

```{r SIR heterogenous model sim}
start <- Sys.time()
results_SIR_het <- vector("list", length = 3)

for (i in 1:3){
  param <- param.net(inf.prob = ppois(n/100*0.4,n/100), 
                    inf.prob.g2 = ppois(n/100*0.7,n/100), 
                    rec.rate = 0.05, 
                    rec.rate.g2 = 0.01)
  
  init <- init.net(i.num = 2, i.num.g2 = 3, r.num = 0, r.num.g2 = 0)
  control <- control.net(type = "SIR", nsteps = 200, nsims = 3, ncores = 5)
  sim <- netsim(est_het, param, init, control) 
  results_SIR_het[[i]] <- as.data.frame(sim, out = "mean")
}

plot(sim, y = c("s.num", "i.num", "r.num"), legend = TRUE)
plot(sim, y = c("s.num", "s.num.g2", "i.num", "i.num.g2", "r.num", "r.num.g2"), legend = TRUE)
plot(sim, type = "network", col.status = TRUE, at = 1, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2", "Recovered g1", "Recovered g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90", "#89da7b", "#89da7b"), pch = c(16, 15, 16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 50, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2", "Recovered g1", "Recovered g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90", "#89da7b", "#89da7b"), pch = c(16, 15, 16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 100, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2", "Recovered g1", "Recovered g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90", "#89da7b", "#89da7b"), pch = c(16, 15, 16, 15, 16, 15))
plot(sim, type = "network", col.status = TRUE, at = 200, sims = 1, shp.g2 = "square", legend = TRUE)
legend("topright", legend = c("Susceptible g1", "Susceptible g2", "Infected g1", "Infected g2", "Recovered g1", "Recovered g2"), col = c("#5cafe7", "#5cafe7", "#e77e90", "#e77e90", "#89da7b", "#89da7b"), pch = c(16, 15, 16, 15, 16, 15))


end <- Sys.time()
end - start
```
## Data Output

```{r write out data to csvs}

average_results <- function(df_list) {

  # Reduce the list by summing up corresponding elements
  summed_df <- Reduce("+", df_list)
  
  # Divide by the number of data frames to get the average
  averaged_df <- summed_df / length(df_list)
  
  return(averaged_df)
}

df_SI <- average_results(results_SI_het)
df_SIV <- average_results(results_SIV_het)
df_SIR <- average_results(results_SIR_het)

write.csv(df_SI, "SI_heterogenous.csv")
write.csv(df_SIV, "SI_vaccine_heterogenous.csv")
write.csv(df_SIR, "SIR_heterogeous.csv")

```